import type { Gig, MockPerson, Venue, PersonDetailData } from "./types";

export const mockGigs: Gig[] = [
  {
    id: "1",
    title: "Melbourne Single Launch",
    date: "Sat Aug 13",
    time: "4pm",
    act: "My Punk Band",
    tour: "Album Tour",
    venue: "Lulie Tavern",
    city: "Melbourne",
    status: "TO RECONCILE",
    description:
      "I am a talented musician/artist with a passion for creating original and captivating works of art. With a keen sense of creativity and a dedication to excellence, I am constantly exploring new techniques and pushing the boundaries of my medium. My specialties include songwriting/composing, performance, and visual art.",
    people: [
      { id: "p1", role: "Guitar", name: "Name Surname", status: "Confirmed", fee: "" },
      { id: "p2", role: "Bass", name: "Name Surname", status: "TBC", fee: "" },
      { id: "p3", role: "Drums", name: "Name Surname", status: "Confirmed", fee: "" },
      { id: "p4", role: "Engineer", name: "Name Surname", status: "TBC", fee: "" },
      { id: "p5", role: "Support", name: "Act Name", status: "TBC", fee: "" },
    ],
    money: {
      gigFee: "$***",
      playerFees: "$250 (recommended fee)",
      supports: "$***",
      promo: "$***",
      rehearsal: "$***",
      production: "$***",
      travel: "$***",
      other: "$***",
      gst: "-",
      superPayable: "$***",
      profitLoss: "$***",
    },
    docs: [
      { id: "d1", name: "Worksheet", type: "Worksheet", completed: false },
      { id: "d2", name: "Setlist", type: "Setlist", completed: true },
      { id: "d3", name: "Stage Plot", type: "Stage Plot", completed: false },
      { id: "d4", name: "Gig Artwork", type: "Gig Artwork", completed: true },
      { id: "d5", name: "Invoice", type: "Invoice", completed: false },
      { id: "d6", name: "Other", type: "Other", completed: false },
    ],
    links: [
      { id: "l1", name: "Tickets", type: "Tickets", url: "#" },
      { id: "l2", name: "Facebook event", type: "Facebook event", url: "#" },
      { id: "l3", name: "Press Release", type: "Press Release", url: "#" },
      { id: "l4", name: "Promo Video", type: "Promo Video", url: "#" },
      { id: "l5", name: "Other", type: "Other", url: "#" },
    ],
  },
  {
    id: "2",
    title: "Fitzroy Street Party",
    date: "Sat Aug 13",
    time: "4pm",
    act: "My Acoustic Duo",
    venue: "Old Bar",
    city: "Fitzroy",
    status: "CONFIRMED",
    description:
      "An intimate acoustic performance showcasing our latest material in a cozy bar setting.",
    people: [
      { id: "p6", role: "Guitar", name: "Alex Johnson", status: "Confirmed", fee: "" },
      { id: "p7", role: "Bass", name: "Sam Wilson", status: "Confirmed", fee: "" },
    ],
    money: {
      gigFee: "$400",
      playerFees: "$200 per person",
      supports: "$100",
      promo: "$50",
      rehearsal: "$0",
      production: "$0",
      travel: "$40",
      other: "$0",
      gst: "$44",
      superPayable: "$40",
      profitLoss: "$110",
    },
    docs: [
      { id: "d7", name: "Worksheet", type: "Worksheet", completed: true },
      { id: "d8", name: "Setlist", type: "Setlist", completed: true },
    ],
    links: [
      { id: "l6", name: "Facebook event", type: "Facebook event", url: "#" },
    ],
  },
  {
    id: "3",
    title: "Summer Festival",
    date: "Sat Aug 20",
    time: "6pm",
    act: "The Electric Band",
    tour: "Festival Circuit",
    venue: "Main Stage",
    city: "Sydney",
    status: "TBC",
    description:
      "Major festival appearance with full production support. Prime evening slot on the main stage.",
    people: [
      { id: "p8", role: "Guitar", name: "Chris Martin", status: "TBC", fee: "" },
      { id: "p9", role: "Bass", name: "Jordan Lee", status: "TBC", fee: "" },
      { id: "p10", role: "Drums", name: "Taylor Swift", status: "Declined", fee: "" },
      { id: "p11", role: "Engineer", name: "Morgan Tech", status: "TBC", fee: "" },
    ],
    money: {
      gigFee: "$***",
      playerFees: "$***",
      supports: "$***",
      promo: "$***",
      rehearsal: "$***",
      production: "$***",
      travel: "$***",
      other: "$***",
      gst: "-",
      superPayable: "$***",
      profitLoss: "$***",
    },
    docs: [],
    links: [],
  },
  {
    id: "4",
    title: "Jazz Night",
    date: "Fri Aug 26",
    time: "8pm",
    act: "Smooth Trio",
    venue: "Blue Note",
    city: "Brisbane",
    status: "ANNOUNCED",
    description:
      "A sophisticated evening of jazz standards and original compositions.",
    people: [
      { id: "p12", role: "Guitar", name: "Miles Davis Jr", status: "Confirmed", fee: "" },
      { id: "p13", role: "Bass", name: "John Coltrane II", status: "Confirmed", fee: "" },
      { id: "p14", role: "Drums", name: "Ella Fitzgerald", status: "Confirmed", fee: "" },
    ],
    money: {
      gigFee: "$600",
      playerFees: "$200 per person",
      supports: "$0",
      promo: "$100",
      rehearsal: "$150",
      production: "$50",
      travel: "$0",
      other: "$0",
      gst: "$90",
      superPayable: "$60",
      profitLoss: "$50",
    },
    docs: [
      { id: "d9", name: "Setlist", type: "Setlist", completed: true },
      { id: "d10", name: "Stage Plot", type: "Stage Plot", completed: false },
    ],
    links: [
      { id: "l7", name: "Tickets", type: "Tickets", url: "#" },
      { id: "l8", name: "Facebook event", type: "Facebook event", url: "#" },
    ],
  },
  {
    id: "5",
    title: "Indie Rock Showcase",
    date: "Thu Sep 1",
    time: "7pm",
    act: "Garage Sound",
    venue: "The Basement",
    city: "Adelaide",
    status: "INVOICED",
    description:
      "High-energy indie rock performance with local support acts.",
    people: [
      { id: "p15", role: "Guitar", name: "River Phoenix", status: "Confirmed", fee: "" },
      { id: "p16", role: "Bass", name: "Ocean Wave", status: "Confirmed", fee: "" },
      { id: "p17", role: "Drums", name: "Storm Cloud", status: "Confirmed", fee: "" },
      { id: "p18", role: "Support", name: "Local Heroes", status: "Confirmed", fee: "" },
    ],
    money: {
      gigFee: "$500",
      playerFees: "$150 per person",
      supports: "$150",
      promo: "$75",
      rehearsal: "$100",
      production: "$100",
      travel: "$80",
      other: "$25",
      gst: "$75",
      superPayable: "$50",
      profitLoss: "-$30",
    },
    docs: [
      { id: "d11", name: "Worksheet", type: "Worksheet", completed: true },
      { id: "d12", name: "Setlist", type: "Setlist", completed: true },
      { id: "d13", name: "Invoice", type: "Invoice", completed: true },
    ],
    links: [],
  },
  {
    id: "6",
    title: "Acoustic Brunch",
    date: "Sun Sep 4",
    time: "11am",
    act: "Sunday Vibes",
    venue: "Garden Cafe",
    city: "Perth",
    status: "RECONCILED",
    description: "Relaxed acoustic set for weekend brunch crowd.",
    people: [
      { id: "p19", role: "Guitar", name: "Sunny Day", status: "Confirmed", fee: "" },
    ],
    money: {
      gigFee: "$200",
      playerFees: "$200",
      supports: "$0",
      promo: "$0",
      rehearsal: "$0",
      production: "$0",
      travel: "$30",
      other: "$0",
      gst: "$20",
      superPayable: "$20",
      profitLoss: "-$50",
    },
    docs: [
      { id: "d14", name: "Worksheet", type: "Worksheet", completed: true },
      { id: "d15", name: "Invoice", type: "Invoice", completed: true },
    ],
    links: [],
  },
  {
    id: "7",
    title: "Rock The Ages",
    date: "Sat Sep 10",
    time: "9pm",
    act: "Classic Rockers",
    tour: "Revival Tour",
    venue: "Thunder Dome",
    city: "Melbourne",
    status: "CANCELLED",
    description: "Classic rock tribute night - CANCELLED due to venue issues.",
    people: [],
    money: {
      gigFee: "$0",
      playerFees: "$0",
      supports: "$0",
      promo: "$0",
      rehearsal: "$0",
      production: "$0",
      travel: "$0",
      other: "$0",
      gst: "-",
      superPayable: "$0",
      profitLoss: "$0",
    },
    docs: [],
    links: [],
  },
  {
    id: "8",
    title: "Electronic Dreams",
    date: "Fri Sep 16",
    time: "10pm",
    act: "DJ Synthwave",
    venue: "Club Neon",
    city: "Sydney",
    status: "TBC",
    description:
      "Electronic music showcase featuring synth-heavy performances and DJ sets.",
    people: [
      { id: "p20", role: "Engineer", name: "Tech Master", status: "TBC", fee: "" },
    ],
    money: {
      gigFee: "$***",
      playerFees: "$***",
      supports: "$***",
      promo: "$***",
      rehearsal: "$***",
      production: "$***",
      travel: "$***",
      other: "$***",
      gst: "-",
      superPayable: "$***",
      profitLoss: "$***",
    },
    docs: [],
    links: [],
  },
];

export const mockVenues: Venue[] = [
  {
    id: "1",
    name: "Lulie Tavern",
    type: "Bar",
    capacity: "150",
    area: "Abbotsford",
    city: "Melbourne",
    state: "VIC",
    streetAddress: "123 Smith Street",
    suburb: "Abbotsford",
    description:
      "A cozy neighborhood bar with great acoustics and a welcoming atmosphere for live music.",
    email: "bookings@lulietavern.com",
    abn: "12345678901",
    phone: "0432 098 789",
    facebook: "facebook.com/lulietavern",
    website: "lulietavern.com",
    spotify: "spotify.com/lulietavern",
    gigs: ["1", "2"],
    playedCount: 5,
    isFavorite: false,
  },
  {
    id: "2",
    name: "The Old Bar",
    type: "Pub",
    capacity: "200",
    area: "Fitzroy",
    city: "Melbourne",
    state: "VIC",
    streetAddress: "74 Johnston Street",
    suburb: "Fitzroy",
    description:
      "Historic venue known for launching emerging artists and hosting unforgettable performances.",
    email: "info@theoldbar.com.au",
    abn: "98765432101",
    phone: "0412 345 678",
    facebook: "facebook.com/theoldbar",
    website: "theoldbar.com.au",
    gigs: ["3"],
    playedCount: 12,
    isFavorite: true,
  },
  {
    id: "3",
    name: "George Lane",
    type: "Live Music Venue",
    capacity: "300",
    area: "St Kilda",
    city: "Melbourne",
    state: "VIC",
    streetAddress: "1 George Lane",
    suburb: "St Kilda",
    description:
      "Premier live music venue with state-of-the-art sound system and intimate setting.",
    email: "bookings@georgelane.com.au",
    abn: "11223344556",
    phone: "0423 456 789",
    website: "georgelane.com.au",
    gigs: [],
    playedCount: 8,
    isFavorite: false,
  },
  {
    id: "4",
    name: "Night Cat",
    type: "Club",
    capacity: "400",
    area: "Fitzroy",
    city: "Melbourne",
    state: "VIC",
    streetAddress: "141 Johnston Street",
    suburb: "Fitzroy",
    description:
      "Iconic nightclub featuring diverse music programming and exceptional production values.",
    email: "info@nightcat.com.au",
    abn: "66778899001",
    phone: "0434 567 890",
    facebook: "facebook.com/nightcat",
    website: "nightcat.com.au",
    spotify: "spotify.com/nightcat",
    gigs: ["4"],
    playedCount: 15,
    isFavorite: true,
  },
  {
    id: "5",
    name: "The Gem",
    type: "Theatre",
    capacity: "500",
    area: "Collingwood",
    city: "Melbourne",
    state: "VIC",
    streetAddress: "58 Easey Street",
    suburb: "Collingwood",
    description:
      "Beautiful heritage-listed theatre with ornate interiors and exceptional acoustics.",
    email: "bookings@thegem.com.au",
    abn: "22334455667",
    phone: "0445 678 901",
    website: "thegem.com.au",
    gigs: [],
    playedCount: 3,
    isFavorite: false,
  },
];

export const mockPeople: MockPerson[] = [
  { id: "1", name: "Sarah Johnson", role: "Lead Vocalist", type: "Band", phone: "+1 555-0101" },
  { id: "2", name: "Mike Chen", role: "Lead Guitar", type: "Band", phone: "+1 555-0102" },
  { id: "3", name: "Alex Rodriguez", role: "Bass Guitar", type: "Band", phone: "+1 555-0103" },
  { id: "4", name: "Emily Davis", role: "Drums", type: "Band", phone: "+1 555-0104" },
  { id: "5", name: "Jordan Lee", role: "Keyboard", type: "Band", phone: "+1 555-0105" },
  { id: "6", name: "Chris Taylor", role: "Backup Vocals", type: "Band", phone: "+1 555-0106" },
  { id: "7", name: "Pat Morgan", role: "Sound Engineer", type: "Crew", phone: "+1 555-0201" },
  { id: "8", name: "Sam Wilson", role: "Lighting Technician", type: "Crew", phone: "+1 555-0202" },
  { id: "9", name: "Casey Brown", role: "Stage Manager", type: "Crew", phone: "+1 555-0203" },
  { id: "10", name: "Jamie White", role: "Tour Manager", type: "Crew", phone: "+1 555-0204" },
  { id: "11", name: "Morgan Black", role: "Guitar Tech", type: "Crew", phone: "+1 555-0205" },
  { id: "12", name: "Riley Green", role: "Drum Tech", type: "Crew", phone: "+1 555-0206" },
  { id: "13", name: "Taylor Blue", role: "Merch Manager", type: "Crew", phone: "+1 555-0207" },
  { id: "14", name: "David Martinez", role: "Booking Agent", type: "Other", phone: "+1 555-0301" },
  { id: "15", name: "Lisa Anderson", role: "Publicist", type: "Other", phone: "+1 555-0302" },
  { id: "16", name: "Tom Jackson", role: "Manager", type: "Other", phone: "+1 555-0303" },
];

export const mockPersonDetails: Record<string, PersonDetailData> = {
  "1": {
    id: "1",
    name: "Sarah Johnson",
    location: "Melbourne",
    roles: ["Lead Vocalist", "Songwriter", "Producer"],
    bands: [
      "Ben Mastryk & His Millions",
      "Country & Western Ramblers",
      "Hana & Jessie Lee's Bad Habits",
    ],
    upcomingGigs: 12,
    toReconcile: 5,
    allTimeGigs: 28,
  },
  "2": {
    id: "2",
    name: "Mike Chen",
    location: "Sydney",
    roles: ["Lead Guitar", "Composer"],
    bands: ["The Electric Dreams", "Midnight Riders"],
    upcomingGigs: 8,
    toReconcile: 3,
    allTimeGigs: 45,
  },
};

export const gigRoles = [
  "Lead Vocals",
  "Guitar",
  "Bass",
  "Drums",
  "Keyboards",
  "Saxophone",
  "Trumpet",
  "Trombone",
  "Violin",
  "Cello",
  "Percussion",
  "Sound Engineer",
  "Lighting Engineer",
  "Stage Manager",
  "Monitor Engineer",
  "FOH Engineer",
  "Support",
  "Manager",
  "Tour Manager",
];
